### ISSUE TITLE
Remote HTTP missing content-type, espeak pronounciation page missing phonemes

### ISSUE THREAD

**Issue by Terramoto** [rhasspy/rhasspy#129]
Hello,

I'm running a rhasspy image on docker and i'm a noob but because i haven't found stuff about the problems i was facing i decided to post it here.

The profile language is pt,

using espeak for TTS, in the pronunciation page generates the following:
`[DEBUG:2020-11-13 18:51:45,661] rhasspyserver_hermes.utils: ['espeak', '--stdout', '-s', '80', '-v', 'pt', '[[]]']`
Which looks like the phonemes are not being passed to the tool, i came to this conclusion because i ran the tool on the terminal and it worked when i provided a word but i see [[]] in the debug it looks like it's suppose to contain the phonemes.

Using Remote HTTPS for Audio Playing sends the audio without Content-Type audio/wav, not exactly sure if it's a problem i've just not been able to process it through node-red, i've notice its just calling a curl so i changed it to Local Command and used:
`curl -H 'Content-Type:audio/wav' --data-binary @- --url http://192.168.137.11:1880/input --connect-timeout 10`
and this seems to do the trick, unfortunately when i set this arguments it breaks the profile as it removes the [] in the 
`"play_arguments":` field:
```
"sounds": {
        "command": {
            "play_arguments": "-H 'Content-Type:audio/wav' --data-binary @- --url http://192.168.137.11:1880/input --connect-timeout 10",
            "play_program": "curl"
        },
        "system": "command"
    },
```
Generating the following error:
```
play_command = [play_program] + profile.get("sounds.command.play_arguments", [])
TypeError: can only concatenate list (not "str") to list
```

**Comment by h4de5** [comment]
I can confirm this problem. when trying to output audio on a remote rhasspy instance it does not work with "Remote HTTP" and the url: `http://satellite:12101/api/play-wav`
but with the command `curl --url http://satellite:12101/api/play-wav --connect-timeout 10 -H 'Content-Type:audio/wav' --data-binary @-` audio is correctly forwarded - thanks for this!

**Comment by synesthesiam** [comment]
The command args issue should be resolved as of 2.5.9. I'll be adding the missing espeak phonemes in 2.5.10. You can copy [this file](https://github.com/synesthesiam/pt-br_pocketsphinx-cmu/blob/master/espeak_phonemes.txt) to your profile for now, if you'd like.

**Comment by h4de5** [comment]
unfortunatelly "Remote HTTP" does not yet work for me in 2.5.9

**Comment by Romkabouter** [comment]
Sorry @h4de5 , just wanted to confirm is this is still an issue in 2.5.11?

**Comment by h4de5** [comment]
this indeed, is still an issue. Just fired up my setup.

the curl call works, but the http call to the same address doesn't
